### ISSUE TITLE
Ability to grep based on metadata

### ISSUE THREAD

**Issue by levex** [nerves-project/ring_logger#133]
Hi @nerves-project!

Thanks for the great library, however I have a use case where I'd like to get the formatted log messages, based on the entries' metadata.

Is this currently possible? If not, I'll start working on a PR.

Ideally something like `RingLogger.grep_metadata(logger_server, :session_id, "abc123", %{})`

Thanks! :-)

**Comment by fhunleth** [comment]
Hi @levex!

This sounds like a useful feature. The best you can do now is to change the formatter to add the `:session_id` to the formatted log message and grep that. See https://github.com/nerves-project/ring_logger#formatting. 

I don't think any of us has strong opinions on the API. What you propose certainly seems good.

Thanks!

**Comment by levex** [comment]
Hi @fhunleth, great, I have a WIP patch ready and will attempt to submit a PR this week. :-)
