### ISSUE TITLE
RingLogger persisting the log data to file as human readable text instead of binary

### ISSUE THREAD

**Issue by blackode** [nerves-project/ring_logger#167]
### Environment

* Elixir version (`elixir -v`):  1.13.4
* Nerves environment: (`mix nerves.env --info`)  
Nerves environment
  MIX_TARGET:   c2
  MIX_ENV:      prod

### Current behavior
Logs are saved as binaries inside the file. I meant to say that they are not human-readable.

### Expected behavior
Logs inside the file have to be human-readable.

**Comment by fhunleth** [comment]
RingLogger's persisted data isn't intended to be human-readable so this is the expected behavior. There are other Elixir and Erlang loggers that persist data in normal text files that probably are a better option for you.
