### ISSUE TITLE
function :RingLogger.init/1 is undefined (module :RingLogger is not available)

### ISSUE THREAD

**Issue by irsanvanwel** [nerves-project/ring_logger#45]
This seems to happen with Erlang/OTP 22 [erts-10.5.2]
See below:
=SUPERVISOR REPORT==== 29-Oct-2019::15:56:20.766534 ===
    supervisor: {local,'Elixir.Logger.Supervisor'}
    errorContext: start_error
    reason: {'EXIT',
                {#{'__exception__' => true,
                   '__struct__' => 'Elixir.RuntimeError',
                   message =>
                       <<"EXIT when installing backend :RingLogger: an exception was raised:\n    ** (UndefinedFunctionError) function :RingLogger.init/1 is undefined (module :RingLogger is not available)\n        :RingLogger.init(:RingLogger)\n        (stdlib) gen_event.erl:473: :gen_event.server_add_handler/4\n        (stdlib) gen_event.erl:318: :gen_event.handle_msg/6\n        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3">>},

**Comment by ConnorRigby** [comment]
Can you post your `config.exs`?

**Comment by fhunleth** [comment]
This sounds like `:ring_logger` isn't in the `mix` dependence list so it's not being included in the OTP release.

**Comment by irsanvanwel** [comment]
It is definitly in there, Im out of office right now so ill share the config and mix config tomorrow (around 7am GMT). On 29 Oct 2019 5:15 PM, Frank Hunleth <notifications@github.com> wrote:This sounds like :ring_logger isn't in the mix dependence list so it's not being included in the OTP release.

**Comment by fhunleth** [comment]
Oh, I see. It says `:RingLogger` with a colon at the front. The colon shouldn't be there since `RingLogger` is the module's name and not `:RingLogger`.

**Comment by irsanvanwel** [comment]
Hi fhunleth think you're right, my bad apologies for that.

**Comment by fhunleth** [comment]
I’m glad it’s fixed!
