### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/ring_logger#6]
When i use the `:console` backend i format my logs ie:
```elixir
config :logger, :console, [
  format: "\n $time $metadata[$level] $levelpad$message\n"
]
```

it'd be nice for  `ring_logger` to either share the same format, or allow configuration of a format.

**Comment by mobileoverlord** [comment]
Ringlogger does allow formatting, but, it’s on a per client basis. It would be nice to allow a default format to be set so when clients omit it, they can get the default one.

**Comment by fhunleth** [comment]
Closing old bug.
